certbot:
  image: certbot/certbot
  container_name: certbot
  volumes:      
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
  depends_on:
    nginx
  networks:
    nginx_net