services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt          # config for certbot certificates
      - ./certbot/www:/var/www/certbot           # for certbot challenge
    restart: unless-stopped
    networks:
      - nginx-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:      
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true